// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI / Migrate use the DIRECT connection (port 5432) — migrations
    // cannot run over the PgBouncer transaction pooler. The runtime client uses
    // the pooled DATABASE_URL via a driver adapter passed to PrismaClient.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
